### ISSUE TITLE
Can you elaborate on the required hardware?

### ISSUE THREAD

**Issue by cdealti** [Cognosec/SecBee#1]
It would be helpful if you could improve the documentation.
1. Why a SDR is needed? I've read the presentation and the whitepaper but it's not clear to me
2. What is the function of the Raspbee?
3. What does this project offer over KillerBee?

Thanks!

**Comment by zu1na** [comment]
1. Why a SDR is needed? I've read the presentation and the whitepaper but it's not clear to me

The SDR is used for sniffing the ZigBee communication and sending direct commands to devices. The whole tool is based on the usage of SDR.
1. What is the function of the Raspbee?

The Raspbee is used for indirect data communication. The Secbee implementation was too slow in our testsetup to perform ACKs in the necessary timeframe. Therefore, we chose to use the Raspbee with our firmware to perform acknowledging and injecting indirect commands.
1. What does this project offer over KillerBee?

SecBee offers sniffing of encrypted traffic on network level, listing of devices and most important predefined commands that can be injected into the network traffic and allow testing of security relevant features such as the insecure rejoin or the usage of the default TC Link Key.

**Comment by cdealti** [comment]
Thanks,
  The SDR is very expensive. I think you could achieve the same using the AVR Raven USB stick also used by Killerbee.

**Comment by ran2** [comment]
After starting SecBee.py, my ubuntu 15.04 received this message.

"ERROR: name 'X3BytesField' is not defined"
Any problem?

**Comment by zu1na** [comment]
Hi,

have you installed all dependencies for scapy-radio and GNU Radio correctly?

What version of GNU Radio do you use?

Is the GNU Radio flow graph running on its own?

Best,
Tobias

**Comment by ran2** [comment]
Hey, Tobias,

I have EZ-wave installed which provides me a modified version of scapy-radio.  After removed the original version of scapy-radio @ https://bitbucket.org/cybertools/scapy-radio/src https://bitbucket.org/cybertools/scapy-radio/src.  The message removed. Thanks

Regards,

Frankie

**Comment by ran2** [comment]
Tobias,

Another questions on the hardware requirement. I have hackrf one but not USRP, should I have to replace the Zigbee.grc USRP Sink/Source with OsmoSDR Source to sniff the ZigBee packets?

Regards

Frankie 
![zigbee grc](https://cloud.githubusercontent.com/assets/10750950/14587132/bf1bfaae-04df-11e6-898c-547f3a914674.png)

**Comment by zu1na** [comment]
Hi Frankie,

yes please replace the UHD source with an osmocom source to use it with HackRF. You will also have to copy the new top_block.py and GRC files to your scapy radio folder.

~/.scapy/radio/Zigbee/

Currently it seems as there are issues with sending packets and the osmocom sink, but sniffing should be fine.

Best,
Tobias
